import { FileText, AlertTriangle, Shield } from 'lucide-react';
import Header from '@/components/Header';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service – AI Detector Free (Usage & Responsibilities)',
  description: 'Review the terms for using AI Detector Free, including acceptable use, limitations, disclaimers, and user responsibilities.',
  alternates: {
    canonical: '/terms',
  },
  openGraph: {
    title: 'Terms of Service – AI Detector Free (Usage & Responsibilities)',
    description: 'Review the terms for using AI Detector Free, including acceptable use, limitations, disclaimers, and user responsibilities.',
    url: 'https://aidetectorfree.app/terms',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Terms of Service – AI Detector Free (Usage & Responsibilities)',
    description: 'Review the terms for using AI Detector Free, including acceptable use, limitations, disclaimers, and user responsibilities.',
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function TermsPage() {
  return (
    <>
      <Header />
      <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">Terms of Service</h1>
          <p className="text-gray-600">Last updated: October 20, 2025</p>
        </div>

        {/* Content */}
        <div className="bg-white rounded-xl shadow-lg p-8 space-y-8">
          {/* Introduction */}
          <section>
            <div className="flex items-center gap-3 mb-4">
              <FileText className="w-6 h-6 text-blue-600" />
              <h2 className="text-2xl font-bold text-gray-900">Agreement to Terms</h2>
            </div>
            <p className="text-gray-700 leading-relaxed">
              By accessing and using AI Content Detector ("the Service"), you agree to be bound by these Terms of Service
              ("Terms"). If you do not agree to these Terms, please do not use the Service. We reserve the right to update
              these Terms at any time, and your continued use constitutes acceptance of any changes.
            </p>
          </section>

          {/* Service Description */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Description of Service</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              AI Content Detector provides two primary services:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
              <li><strong>AI Content Detection:</strong> Analyzes text to estimate the likelihood that it was generated by artificial intelligence using advanced machine learning algorithms</li>
            </ul>
            <p className="text-gray-700 leading-relaxed mt-4">
              Our services use third-party AI detection technology and are subject to the limitations 
              inherent in AI analysis systems.
            </p>
          </section>

          {/* User Responsibilities */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">User Responsibilities</h2>
            <p className="text-gray-700 leading-relaxed mb-4">By using the Service, you agree to:</p>
            <ul className="space-y-3 text-gray-700">
              <li className="flex items-start gap-2">
                <span className="text-blue-600 font-bold mt-1">•</span>
                <span>Use the Service only for lawful purposes and in compliance with all applicable laws</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-blue-600 font-bold mt-1">•</span>
                <span>Not submit content that violates intellectual property rights, privacy rights, or other legal rights of third parties</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-blue-600 font-bold mt-1">•</span>
                <span>Not submit content that is illegal, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-blue-600 font-bold mt-1">•</span>
                <span>Not attempt to circumvent rate limits, security measures, or other protective systems</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-blue-600 font-bold mt-1">•</span>
                <span>Not use automated systems (bots, scrapers) to access the Service without permission</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-blue-600 font-bold mt-1">•</span>
                <span>Not reverse-engineer, decompile, or attempt to extract the source code of the Service</span>
              </li>
            </ul>
          </section>

          {/* Accuracy Disclaimer */}
          <section>
            <div className="flex items-center gap-3 mb-4">
              <AlertTriangle className="w-6 h-6 text-yellow-600" />
              <h2 className="text-2xl font-bold text-gray-900">Accuracy and Limitations</h2>
            </div>
            <div className="bg-yellow-50 border-l-4 border-yellow-500 p-4 mb-4">
              <p className="text-yellow-800 font-medium">
                ⚠️ AI detection and plagiarism checking are NOT 100% accurate
              </p>
            </div>
            <p className="text-gray-700 leading-relaxed mb-4">
              <strong>Important:</strong> Our Service provides probabilistic estimates and should be used as a tool to
              assist in content evaluation, not as definitive proof. Results may include:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
              <li><strong>False Positives:</strong> Human-written content (especially formal or technical writing) may be incorrectly flagged as AI-generated</li>
              <li><strong>False Negatives:</strong> AI-generated content may not always be detected, particularly if it has been heavily edited</li>
              <li><strong>Plagiarism Limitations:</strong> We can only search indexed web pages; content not indexed or from private sources will not be detected</li>
              <li><strong>Fair Use:</strong> Legitimate quotations, citations, and public domain content may be flagged as plagiarism</li>
            </ul>
            <p className="text-gray-700 leading-relaxed mt-4">
              <strong>You agree to:</strong> Use human judgment and consider context when evaluating results. Do not rely
              solely on our Service for critical decisions such as academic integrity violations, hiring decisions, or
              legal proceedings.
            </p>
          </section>

          {/* Usage Limits */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Usage Limits and Restrictions</h2>
            <div className="space-y-3 text-gray-700">
              <p><strong>Text Limits:</strong></p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li>Maximum 50,000 characters per request</li>
                <li>Plagiarism checking requires minimum 300 words</li>
              </ul>
              <p className="mt-4"><strong>Rate Limits:</strong></p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li>AI Detection: 10 requests per minute per IP address</li>
                <li>Plagiarism Checking: 5 requests per minute per IP address</li>
              </ul>
              <p className="mt-4">
                We reserve the right to modify these limits or suspend access for users who abuse the Service.
              </p>
            </div>
          </section>

          {/* Intellectual Property */}
          <section>
            <div className="flex items-center gap-3 mb-4">
              <Shield className="w-6 h-6 text-green-600" />
              <h2 className="text-2xl font-bold text-gray-900">Intellectual Property</h2>
            </div>
            <p className="text-gray-700 leading-relaxed mb-4">
              <strong>Your Content:</strong> You retain all rights to the text you submit for analysis. By submitting
              content, you grant us a temporary, non-exclusive license to process it through our Service and third-party
              providers for the sole purpose of providing analysis results.
            </p>
            <p className="text-gray-700 leading-relaxed">
              <strong>Our Service:</strong> The Service, including its design, code, and trademarks, is owned by us and
              protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works
              without permission.
            </p>
          </section>

          {/* Third-Party Services */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Third-Party Services</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              Our Service relies on third-party AI detection technology for content analysis. By using our Service, you acknowledge that:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
              <li>Your content will be transmitted to third-party servers for analysis</li>
              <li>Third-party service providers' terms of service and privacy policies may apply</li>
              <li>We are not responsible for third-party providers' actions, errors, or service availability</li>
              <li>Service interruptions may occur due to third-party provider issues</li>
            </ul>
          </section>

          {/* Disclaimer of Warranties */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Disclaimer of Warranties</h2>
            <p className="text-gray-700 leading-relaxed">
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
              INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
              NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY SECURE.
            </p>
          </section>

          {/* Limitation of Liability */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Limitation of Liability</h2>
            <p className="text-gray-700 leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR
              INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM YOUR USE OF
              THE SERVICE.
            </p>
          </section>

          {/* Indemnification */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Indemnification</h2>
            <p className="text-gray-700 leading-relaxed">
              You agree to indemnify and hold harmless AI Content Detector, its operators, and affiliates from any claims,
              damages, losses, liabilities, and expenses (including legal fees) arising from your use of the Service, your
              violation of these Terms, or your violation of any rights of third parties.
            </p>
          </section>

          {/* Termination */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Termination</h2>
            <p className="text-gray-700 leading-relaxed">
              We reserve the right to suspend or terminate your access to the Service at any time, for any reason,
              including violation of these Terms. Upon termination, all licenses and rights granted to you will immediately
              cease.
            </p>
          </section>

          {/* Governing Law */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Governing Law</h2>
            <p className="text-gray-700 leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of the jurisdiction where the
              Service is operated, without regard to conflict of law principles.
            </p>
          </section>

          {/* Contact */}
          <section className="bg-gray-50 border border-gray-200 rounded-lg p-6">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Contact Information</h2>
            <p className="text-gray-700 leading-relaxed">
              If you have questions about these Terms, please contact us.
            </p>
          </section>
        </div>
      </div>
    </div>
    </>
  );
}
